#+AUTHOR: Mohamed Tarek
#+EMAIL: m96tarek@gmail.com


* Introduction:
a Django REST project, a peer-to-peer lending platform.
The project facilitates the loan application and approval process, including the management of loan funding and repayment

* Use Case:
One of the borrowers has submitted a loan request for $5,000 to be repaid over 6 months. They have received an offer from one of the lenders on the platform with a 15% Annual Interest Rate. Additionally, a $3.75 fee will be added to the total loan amount to be paid by the lender.

* installation & usage:
** Requirements:
- python > 3.9
- postgreSQL
  + these instructions assume that you have postgreSQL installed and the server running
- poetry (optional)
  + there's a requirements file for non poetry users
-

** instructions:
*** First, we need to clone this repo locally:
#+begin_src sh
git clone https://github.com/xeros-and-ones/lending-platform-django.git
#+end_src

*** we ~cd~ into the clone directory

*** init a virtual environment in the root project directory where the =requirements.txt= exists
**** for poetry:
Simply Run
#+begin_src shell
poetry install
#+end_src

**** or you can use python's venv:
#+begin_src shell
python -m venv .venv
#+end_src

*** installing dependecies:
poetry users already have installed the dependecies via the =pyproject.toml=

**** for venv users, the next step, is to source the venv
***** Linux
#+begin_src shell
source .venv/bin/activate
#+end_src

***** Windows
#+begin_src shell
.\.venv\Sripts\activate
#+end_src


**** then to install the dependecies, run:
#+begin_src shell
pip install -r requirements.txt
#+end_src

*** creating env file for the secrets:
#+begin_src shell
SECRET_KEY=django-insecure-r%-n+$usr!f6=!ke)nu_vsg$p-qoi9200^y2yuk@40&l(9uqbx
DEBUG=True
DB_NAME= #<name of database you created>
DB_USER=postgres
DB_PASSWORD= #<password you create>
DB_HOST= #<host_name>
DB_PORT= #<port>
#+end_src
