# Generated by Django 5.0 on 2023-12-28 05:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_loans", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="amount",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="loan",
            name="period",
            field=models.IntegerField(default=6),
        ),
    ]
