# Generated by Django 5.0 on 2023-12-28 06:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_loans", "0002_alter_loan_amount_alter_loan_period"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="interest_rate",
            field=models.FloatField(default=15),
        ),
    ]
