# Generated by Django 5.0 on 2023-12-28 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_loans", "0004_alter_loan_interest_rate"),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingOffers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "offers",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api_loans.offer",
                    ),
                ),
            ],
        ),
    ]
